### ISSUE TITLE
[META] Remove namespace from cluster-scoped/non-namespaced resources

### ISSUE THREAD

**Issue by QuingKhaos** [bitnami/charts#8434]
**Which chart**:

- [ ] `bitnami/argo-cd`
- [ ] `bitnami/argo-workflows`
- [ ] `bitnami/concourse`
- [ ] `bitnami/contour-operator`
- [ ] `bitnami/contour`
- [ ] `bitnami/kubewatch`
- [ ] `bitnami/metrics-server`
- [ ] `bitnami/nginx-ingress-controller`
- [x] `bitnami/rabbitmq-cluster-operator`
  - #8414
- [ ] `bitnami/wavefront-hpa-adapter`

**Describe the bug**

Cluster-scoped/non-namespaced resources like `ClusterRole` and `ClusterRoleBinding` must not have a namespace set. Most of the k8s tools are not so strict about having the namespace set on a cluster-scoped resource manifest.

Except the [`agentk`](https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/tree/master/) of the GitLab Kubernetes Agent which is very strict on that:

```
{"level":"error","time":"2021-12-14T13:39:32.245Z","msg":"Failed to decode GitOps objects","mod_name":"gitops","project_id":"<redacted>/manifests","agent_id":<redacted>,"error":"resource is cluster-scoped but has a non-empty namespace \"rabbitmq-operator\"","commit_id":"<redacted>"}
```

**To Reproduce**

1. Have a GitLab project with the [GitLab Kubernetes Agent](https://docs.gitlab.com/ee/user/clusters/agent/) installed.
2. Render a chart with e.g. into the repo with the agent installed
   ```helm template --namespace rabbitmq-operator rabbitmq-cluster-operator bitnami/rabbitmq-cluster-operator```
3. Commit and push on the default branch
4. Wait for the agent in the cluster to pick up the changes and the logs should reproduce the error.

**Expected behavior**

Cluster-scoped resources shouldn't get rendered with the release namespace set and the GitLab Kubernetes Agent can process them gracefully.

**Versions affected**:

```
agentk v14.5.0
sigs.k8s.io/cli-utils v0.26.1
```

**Additional context**

Doing a deep-dive on the agent code, the [`syncDecoder.Decode()`](https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/blob/v14.5.0/internal/module/gitops/agent/sync_decoder.go#L44-45) function uses the `sigs.k8s.io/cli-utils/pkg/manifestreader`, so official k8s Go libraries. This is an expected error, when dealing with Kubernetes manifests in Go. The sync decoder tests even show that as expected [happy path](https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/blob/v14.5.0/internal/module/gitops/agent/sync_decoder_test.go#L121-130).

Yes, it's something new to deal with it, especially considering other tools can handle this more gracefully.

**Comment by QuingKhaos** [comment]
Scanned through all charts and of all charts using cluster-scoped resources about half of them has a namespace set on them.

**Comment by rafariossaa** [comment]
Hi @QuingKhaos ,
  Thanks for spotting this. We are looking into this and which is the best approach to fix it in our charts.
  We will come back as soon as we have news.

**Comment by juan131** [comment]
@QuingKhaos thanks for bringing this up! As you mentioned there's no reason to include the namespace in those cluster-scoped K8s objects.

**Comment by rafariossaa** [comment]
@QuingKhaos , Thanks for coming back, we will be glad to review and merge it.
